name:                plutus-contracts
version:             0.1.0.0
github:              "ArsCodeAmatoria/rugrun"
license:             BSD3
author:              "RugRun Team"
maintainer:          "team@rugrun.io"
copyright:           "2023 RugRun Team"

description:         Plutus smart contracts for the RugRun game

dependencies:
- base >= 4.9 && < 5
- aeson
- bytestring
- cardano-api
- containers
- data-default
- plutus-ledger
- plutus-ledger-api
- plutus-tx
- plutus-tx-plugin
- plutus-script-utils
- serialise
- text
- time
- directory
- filepath
- lens
- plutus-core
- plutus-ledger-constraints
- random
- base16-bytestring

ghc-options:
  - -Wall
  - -fobject-code
  - -fno-ignore-interface-pragmas
  - -fno-omit-interface-pragmas
  - -fno-strictness
  - -fno-spec-constr
  - -fno-specialise
  - -fexpose-all-unfoldings

library:
  source-dirs: src

executables:
  plutus-contracts:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - plutus-contracts 